### PR TITLE
Write file in new stream, reuse previous game

### PR DESCRIPTION
**Pull request by adrian-kong**
Had some issues with add-eco for
```
[Event "2019-world-rapid-championship"]
[White "Zubov, Alexander"]
[Black "Carlsen, Magnus"]
[WhiteFideId "14109409"]
[BlackFideId "1503014"]
[Result "0-1"]
[Round "09"]
[Date "Fri Dec 27 2019"]
[WhiteClock "0:00:18"]
[BlackClock "0:03:55"]


1. d4  Nf6 2. Nf3  d5 3. c4  e6 4. e3  a6 5. b3  c5 6. Bb2  cxd4 7. exd4  Nc6 8. Nbd2  g6 9. Bd3  Bg7 10. Qe2  O-O 11. O-O  b6 12. Rad1  Bb7 13. Rfe1  dxc4 14. bxc4  b5 15. c5  Qc7 16. Ne4  Nxe4 17. Bxe4  Ne7 18. Bxb7  Qxb7 19. d5  Nxd5 20. Bxg7  Kxg7 21. Qb2+  Kg8 22. Ne5  Rfd8 23. c6  Qc7 24. h4  h5 25. Rd4  Nb6 26. g4  Rxd4 27. Qxd4  Rd8 28. Qe4  hxg4 29. h5  g3 30. fxg3  Nc4 31. Nxc4  Qxg3+ 32. Kf1  bxc4 33. hxg6  Rd2 34. gxf7+  Kf8 35. Re2  Rd1+ 36. Re1  Rxe1+ 37. Qxe1  Qf3+ 38. Qf2  Qxc6 39. Qf6  Qe4 40. Kg1  Qg4+ 41. Kh2  a5 42. Qd8+  Kxf7 43. Qxa5  Qe2+ 44. Kg3  Qe3+ 45. Kg4  c3 46. Qc7+  Kg6 47. Qc4  Qe5 48. a4  Qf5+ 49. Kg3  c2 0-1
```

Would output 

```
[Event "2019-world-rapid-championship"]
[Site "?"]
[Date "Fri Dec 27 2019"]
[Round "09"]
[White "Zubov, Alexander"]
[Black "Carlsen, Magnus"]
[Result "0-1"]
[BlackClock "0:03:55"]
[BlackFideId "1503014"]
[WhiteClock "0:00:18"]
[WhiteFideId "14109409"]

0-1

[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "0-1"]
[ECO "D02"]
[Opening "Queen's pawn game"]

1. d4 Nf6 2. Nf3 d5 3. c4 e6 4. e3 a6 5. b3 c5 6. Bb2 cxd4 7. exd4 Nc6 8. Nbd2 g6 9. Bd3 Bg7 10. Qe2 O-O 11. O-O b6 12. Rad1 Bb7 13. Rfe1 dxc4 14. bxc4 b5 15. c5 Qc7 16. Ne4 Nxe4 17. Bxe4 Ne7 18. Bxb7 Qxb7 19. d5 Nxd5 20. Bxg7 Kxg7 21. Qb2+ Kg8 22. Ne5 Rfd8 23. c6 Qc7 24. h4 h5 25. Rd4 Nb6 26. g4 Rxd4 27. Qxd4 Rd8 28. Qe4 hxg4 29. h5 g3 30. fxg3 Nc4 31. Nxc4 Qxg3+ 32. Kf1 bxc4 33. hxg6 Rd2 34. gxf7+ Kf8 35. Re2 Rd1+ 36. Re1 Rxe1+ 37. Qxe1 Qf3+ 38. Qf2 Qxc6 39. Qf6 Qe4 40. Kg1 Qg4+ 41. Kh2 a5 42. Qd8+ Kxf7 43. Qxa5 Qe2+ 44. Kg3 Qe3+ 45. Kg4 c3 46. Qc7+ Kg6 47. Qc4 Qe5 48. a4 Qf5+ 49. Kg3 c2 0-1
```

Source: https://www.kaggle.com/datasets/liury123/chess-game-from-12-top-players

This was what I did to output

```
[Event "2019-world-rapid-championship"]
[Site "?"]
[Date "Fri Dec 27 2019"]
[Round "09"]
[White "Zubov, Alexander"]
[Black "Carlsen, Magnus"]
[Result "0-1"]
[BlackClock "0:03:55"]
[BlackFideId "1503014"]
[ECO "D02"]
[Opening "Queen's pawn game"]
[WhiteClock "0:00:18"]
[WhiteFideId "14109409"]

1. d4 Nf6 2. Nf3 d5 3. c4 e6 4. e3 a6 5. b3 c5 6. Bb2 cxd4 7. exd4 Nc6 8. Nbd2 g6 9. Bd3 Bg7 10. Qe2 O-O 11. O-O b6 12. Rad1 Bb7 13. Rfe1 dxc4 14. bxc4 b5 15. c5 Qc7 16. Ne4 Nxe4 17. Bxe4 Ne7 18. Bxb7 Qxb7 19. d5 Nxd5 20. Bxg7 Kxg7 21. Qb2+ Kg8 22. Ne5 Rfd8 23. c6 Qc7 24. h4 h5 25. Rd4 Nb6 26. g4 Rxd4 27. Qxd4 Rd8 28. Qe4 hxg4 29. h5 g3 30. fxg3 Nc4 31. Nxc4 Qxg3+ 32. Kf1 bxc4 33. hxg6 Rd2 34. gxf7+ Kf8 35. Re2 Rd1+ 36. Re1 Rxe1+ 37. Qxe1 Qf3+ 38. Qf2 Qxc6 39. Qf6 Qe4 40. Kg1 Qg4+ 41. Kh2 a5 42. Qd8+ Kxf7 43. Qxa5 Qe2+ 44. Kg3 Qe3+ 45. Kg4 c3 46. Qc7+ Kg6 47. Qc4 Qe5 48. a4 Qf5+ 49. Kg3 c2 0-1
```

Also closes read stream before opening write stream, (might be better for performance? keeping IO open while reading etc... not too sure) but allows overwriting file.

### CODE REVIEW

**Comment by fsmosca** [comment]
Thanks I will check this.

**Comment by fsmosca** [comment]
Your input pgn is not according to [pgn](https://github.com/fsmosca/PGN-Standard/blob/master/PGN-Standard.txt) standard. There is an extra empty line between the last header tag and the beginning of movetext section. It should only be one empty line.

### The incorrect input pgn

```
[Event "2019-world-rapid-championship"]
[White "Zubov, Alexander"]
[Black "Carlsen, Magnus"]
[WhiteFideId "14109409"]
[BlackFideId "1503014"]
[Result "0-1"]
[Round "09"]
[Date "Fri Dec 27 2019"]
[WhiteClock "0:00:18"]
[BlackClock "0:03:55"]


1. d4  Nf6 2. Nf3  d5 3. c4  e6 4. e3  a6 5. b3  c5 6. Bb2  cxd4 7. exd4  Nc6 8. Nbd2  g6 9. Bd3  Bg7 10. Qe2  O-O 11. O-O  b6 12. Rad1  Bb7 13. Rfe1  dxc4 14. bxc4  b5 15. c5  Qc7 16. Ne4  Nxe4 17. Bxe4  Ne7 18. Bxb7  Qxb7 19. d5  Nxd5 20. Bxg7  Kxg7 21. Qb2+  Kg8 22. Ne5  Rfd8 23. c6  Qc7 24. h4  h5 25. Rd4  Nb6 26. g4  Rxd4 27. Qxd4  Rd8 28. Qe4  hxg4 29. h5  g3 30. fxg3  Nc4 31. Nxc4  Qxg3+ 32. Kf1  bxc4 33. hxg6  Rd2 34. gxf7+  Kf8 35. Re2  Rd1+ 36. Re1  Rxe1+ 37. Qxe1  Qf3+ 38. Qf2  Qxc6 39. Qf6  Qe4 40. Kg1  Qg4+ 41. Kh2  a5 42. Qd8+  Kxf7 43. Qxa5  Qe2+ 44. Kg3  Qe3+ 45. Kg4  c3 46. Qc7+  Kg6 47. Qc4  Qe5 48. a4  Qf5+ 49. Kg3  c2 0-1
```

### The correct pgn

```
[Event "2019-world-rapid-championship"]
[White "Zubov, Alexander"]
[Black "Carlsen, Magnus"]
[WhiteFideId "14109409"]
[BlackFideId "1503014"]
[Result "0-1"]
[Round "09"]
[Date "Fri Dec 27 2019"]
[WhiteClock "0:00:18"]
[BlackClock "0:03:55"]

1. d4  Nf6 2. Nf3  d5 3. c4  e6 4. e3  a6 5. b3  c5 6. Bb2  cxd4 7. exd4  Nc6 8. Nbd2  g6 9. Bd3  Bg7 10. Qe2  O-O 11. O-O  b6 12. Rad1  Bb7 13. Rfe1  dxc4 14. bxc4  b5 15. c5  Qc7 16. Ne4  Nxe4 17. Bxe4  Ne7 18. Bxb7  Qxb7 19. d5  Nxd5 20. Bxg7  Kxg7 21. Qb2+  Kg8 22. Ne5  Rfd8 23. c6  Qc7 24. h4  h5 25. Rd4  Nb6 26. g4  Rxd4 27. Qxd4  Rd8 28. Qe4  hxg4 29. h5  g3 30. fxg3  Nc4 31. Nxc4  Qxg3+ 32. Kf1  bxc4 33. hxg6  Rd2 34. gxf7+  Kf8 35. Re2  Rd1+ 36. Re1  Rxe1+ 37. Qxe1  Qf3+ 38. Qf2  Qxc6 39. Qf6  Qe4 40. Kg1  Qg4+ 41. Kh2  a5 42. Qd8+  Kxf7 43. Qxa5  Qe2+ 44. Kg3  Qe3+ 45. Kg4  c3 46. Qc7+  Kg6 47. Qc4  Qe5 48. a4  Qf5+ 49. Kg3  c2 0-1
```

Also the Date tag value is not according to standard. It should be:

```
[Date "2019.12.27"]
```

But the cause why python chess does not parse the game correctly is because of the two empty lines.

```
[BlackClock "0:03:55"]


1. d4  Nf6 2. Nf3  d5 3. c4  e6 4. e3  a6 5. b3  c5 6. Bb2 ...
```

**Comment by adrian-kong** [comment]
> Your input pgn is not according to [pgn](https://github.com/fsmosca/PGN-Standard/blob/master/PGN-Standard.txt) standard. There is an extra empty line between the last header tag and the beginning of movetext section. It should only be one empty line.

Interesting, this data was from https://www.kaggle.com/datasets/liury123/chess-game-from-12-top-players
These were the changes I did in order to extract all the openings in the datasets.
Not sure if this PR is necessary depending if you want to enforce the pgn standard but thought to be nice with having write stream outside of read stream to allow overwriting files

**Comment by fsmosca** [comment]
> Interesting, this data was from https://www.kaggle.com/datasets/liury123/chess-game-from-12-top-players These were the changes I did in order to extract all the openings in the datasets. Not sure if this PR is necessary depending if you want to enforce the pgn standard but thought to be nice with having write stream outside of read stream to allow overwriting files

Sorry but I cannot take the PR. I favor following the pgn standard.
It is easy to clean or correct the errors in the pgn file. You can use [pgn-extract](https://www.cs.kent.ac.uk/people/staff/djb/pgn-extract/). This program can also supply eco code to the game.

pgnhelper is in overwrite mode when writing the ouput from add-eco operation.

**Pull request closed without merging**
